language: node_js
node_js:
  - '0.11'
before_install: 
  - npm install -g bower grunt-cli karma
  - npm cache clean && npm install gruntjs/grunt-contrib-imagemin
  - npm install imagemin-optipng
  - bower install
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - gem install sass
  - gem install compass
before_script: grunt build
services: mongodb